# weather_api_schema.yaml
openapi: 3.0.0
info:
  title: Weather API
  version: 1.0.0
  description: API for getting weather information

paths:
  /weather:
    get:
      summary: Get weather for a city
      description: Returns current weather conditions for a specified city
      operationId: getWeather
      parameters:
        - name: city
          in: query
          description: City name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  city:
                    type: string
                  temperature:
                    type: number
                  condition:
                    type: string
                  humidity:
                    type: number
